name: Build and Release Artifacts
on: push

jobs:
  matrix_prep:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1

      - name: Set matrix
        id: set-matrix
        uses: JoshuaTheMiller/conditional-build-matrix@0.0.1
        with:
          filter: '[?run==`${{ env.BRANCH_NAME }}` || run==`always`]'


  build:
    needs: matrix_prep

    strategy:
      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: gradle

      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build artifacts
        run: ./gradlew build

      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '16' }} # Only upload artifacts built from Java 16 on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/


  release:
    needs: build

    runs-on: ubuntu-latest

    if: contains(github.ref, 'release')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Read version from gradle.properties
        id: read_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'base_version'

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: Artifacts
          path: bin

      - name: Delete dev and sources artifacts
        run: |
          find bin/ -name '*-dev.jar' -delete
          find bin/ -name '*-sources.jar' -delete

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v1.0.0
        continue-on-error: true
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Make and upload release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
          tag_name: v${{ steps.read_version.outputs.value }}
          fail_on_unmatched_files: false
          body: |
            ${{ steps.changelog.outputs.changelog }}

            Make sure to read the [README](README.md) for instructions on how this mod works and how to use it.

      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'temurin'
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Publish artifacts
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
